import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex fixed w-full h-16 items-center justify-center bg-orange-500 text-black">
          <h1 className="text-2xl font-bold">Hacker News</h1>
        </nav>
        <div className="h-16" />
        {children}
      </body>
    </html>
  );
}
